#!/bin/sh

if [ $# -ne 1 ]; then
    echo "usage: `basename $0` directory" > /dev/stderr
    exit 1
fi
if [ ! -d "$1" ]; then
    echo "`basename $0`: $1: No such directory" > /dev/stderr
    exit 1
fi

find "$1" -maxdepth 1 -type d | sed '1d' | {
    DIR=
    NODIR=true
    while read DIR; do
        $0 "$DIR"
        NODIR=false
    done
    $NODIR && echo "$1"
}
exit 0